"use strict";

const url = require("url");
const moment = require("moment");
const querystring = require("querystring");
const node_fetch_cookies = require('fetch-cookie')(require('node-fetch'));
const node_fetch = require('node-fetch');
const fs = require("fs");
const cheerio = require("cheerio");


//This file contains working versions of iceberg methods
//The modules included in this file are available on the iceberg environment
//Do not edit this file
//Ensure all the required libraries are installed in your environment


exports.fetch = async function (requestURL, requestOptions) {
    console.log("fetch --", requestURL);
    return await node_fetch(requestURL, requestOptions);
};

exports.defaultFetchURL = async function ({canonicalURL, headers}) {
    console.log("defaultFetchURL --", canonicalURL);
    let requestOptions = {method: "GET", headers};
    return [await node_fetch(canonicalURL, requestOptions).then(response => {
        return {
            canonicalURL,
            request: Object.assign({URL: canonicalURL}, requestOptions),
            response
        };
    })
    ]
};

exports.fetchWithCookies = async function (requestURL, requestOptions) {
    console.log("fetchWithCookies --", requestURL);
    return await node_fetch_cookies(requestURL, requestOptions);
};