"use strict";

// const url = require("url");
// const moment = require("moment");
// const querystring = require("querystring");
// const node_fetch = require('node-fetch');
// const fs = require("fs");
// const cheerio = require("cheerio");
// const node_fetch_cookies = require('fetch-cookie')(require('node-fetch'));

import url from 'url';
import moment from 'moment';
import * as querystring from 'querystring';
import node_fetch from 'node-fetch';
import fs from 'fs';
import { load } from 'cheerio';
import fetchCookies from 'fetch-cookie';

const node_fetch_cookies = fetchCookies(node_fetch)


//This file contains working versions of iceberg methods
//The modules included in this file are available on the iceberg environment
//Do not edit this file, make a copy if you want to run tests
//Ensure all the modules are installed in your environment


exports.fetch = async function (requestURL, requestOptions) {
    console.log("fetch --", requestURL);
    return await node_fetch(requestURL, requestOptions);
};
exports.defaultFetchURL = async function ({ canonicalURL, headers }) {
    console.log("defaultFetchURL --", canonicalURL);
    let requestOptions = { method: "GET", headers };
    return [await node_fetch(canonicalURL, requestOptions).then(response => {
        return {
            canonicalURL,
            request: Object.assign({ URL: canonicalURL }, requestOptions),
            response
        };
    })
    ]
};
exports.fetchWithCookies = async function (requestURL, requestOptions) {
    console.log("fetchWithCookies --", requestURL);
    return await node_fetch_cookies(requestURL, requestOptions);
};
